### GET all contacts
GET http://localhost:3000/api/contacts
Accept: application/json

### GET contact by ID
GET http://localhost:3000/api/contacts/{{id}}
Accept: application/json

### POST new contact
POST http://localhost:3000/api/contacts
Content-Type: application/json

{
  "firstName": "Alice",
  "lastName": "Malabi",
  "email": "alice@example.com",
  "favoriteColor": "Blue",
  "birthday": "2002-01-01"
}

### PUT update contact
PUT http://localhost:3000/api/contacts/{{id}}
Content-Type: application/json

{
  "favoriteColor": "Red"
}

### DELETE contact
DELETE http://localhost:3000/api/contacts/{{id}}
